apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: snapcd-runner

resources:
  - namespace.yaml
  - runner.yaml

configMapGenerator:
  - name: snapcd-runner-config
    files:
      - appsettings.json=config/appsettings.json
  - name: snapcd-runner-ssh
    files:
      - known_hosts=config/known_hosts
  - name: snapcd-runner-hooks
    files:
      - config/preapproved-hooks/sample.sh

secretGenerator:
  - name: snapcd-runner-ssh-key
    files:
      - id_rsa=config/id_rsa
    type: Opaque
  - name: snapcd-runner-credentials
    envs:
      - config/runner-secret.env
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true
