apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: snapcd-server

resources:
  - namespace.yaml
  - sql-server.yaml
  - redis.yaml
  - server.yaml

secretGenerator:
  - name: snapcd-server-config
    files:
      - appsettings.json=config/appsettings.json
    type: Opaque
  - name: sqlserver-credentials
    envs:
      - config/sql-secret.env
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true
