apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: snapcd-agent

resources:
  - namespace.yaml
  - agent.yaml
  - sidecar-claude.yaml

configMapGenerator:
  - name: snapcd-agent-config
    files:
      - appsettings.json=config/appsettings.json

secretGenerator:
  - name: snapcd-agent-credentials
    envs:
      - config/agent-secret.env
    type: Opaque
  - name: snapcd-agent-sidecar-claude-credentials
    envs:
      - config/sidecar-claude-secret.env
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true
